# Generated by Django 4.1.10 on 2023-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADIT', '0002_student_phone_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50, null=bool),
        ),
    ]
